name: ci

on:  # yamllint disable-line rule:truthy
  - push

jobs:

  build:
    container: cariad/ci:1.4.0
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: cache-venv
        name: Get cached virtual environment
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-venv-${{ hashFiles('Pipfile.lock') }}
          path: ~/.local/share/virtualenvs

      - if: steps.cache-venv.outputs.cache-hit != 'true'
        name: Create virtual environment
        run: pipenv sync --dev

      - name: Build
        run: pipenv run ./build.sh

      - name: Archive distributable
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: aws-vpc-peering-demo.zip
          retention-days: 1

  test_publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Publish
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_content_type: application/zip
          asset_name: aws-vpc-peering-demo.zip
          asset_path: aws-vpc-peering-demo.zip
          upload_url: ${{ steps.get_release.outputs.upload_url }}
